### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by purgatoryforcookies** [solita/kanaliiga-rl-discord-bot#35]
Update readme. Some of the updates include at least (but not limited to)

- RL Captain & RL Organisers roles and their abilities to use commands
- Configurable time limit for clearing up old tasks from the queue
- How time limit works, why is it there

- [x] Update slash commands (rl_ prefix, new commands) NEW: /rl_check, /rl_archive?? this has no name yet, see ticket #46 
- [x] Instructions for captains how to upload replays 
- [x] Instructions for setting Default auth link to None (see comments below)
- [x] Language check
- [x] Maximum number of replays per post, env var and configurability. #44 
- [x] Default Authorization Link should be set to 'None' in the Developer Portal, ensure bot isn't public and note that invite 
- [x] .env TARGET_CHANNEL_NAME and what it does, why is it there
link should *not* be shared

**Comment by Juholei** [comment]
Update also the instructions that are given to captains for instructing how to upload replays (current instructions are posted in Slack).

**Comment by vicontiveros00** [comment]
Add somewhere to documentation that the Default Authorization Link should be set to 'None' in the Developer Portal to keep bot from being invited to other servers

**Comment by Juholei** [comment]
Document also in the readme how to run this in Docker (building the image and then running it and passing the configuration to the container)
