### ISSUE TITLE
Mark post as ready

### ISSUE THREAD

**Issue by Juholei** [solita/kanaliiga-rl-discord-bot#46]
Make it possible for the captain to mark the post as ready with a slash command. After it has been marked as ready, the bot will mark will close the post and not handle it any further. After replays have been uploaded in a post, the bot could suggest to the captain that if everything is done, mark the post ready with the slash command.

**Comment by vicontiveros00** [comment]
@Juholei Who should be granted permission to use that command? RL Captain _and_ RL Organizer or just the captain/organizer?

**Comment by Juholei** [comment]
I think both in this case
